# Site settings
title: Kelli K. Mullane, Ph.D.
subtitle: Research Scientist | Bioinformatician
email: kellikmullane@gmail.com
description: A FREE AND FULLY RESPONSIVE SITE TEMPLATE 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: Encinitas
state: CA
zip_code: 92024
country: United States of America
phone: +1 (714) 272-4442

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/kellikmullane
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/kelli-mullane
pinterest_url:
slack_url:
twitter_url: https://twitter.com/lab_witch_

# Build settings
markdown: kramdown
